//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquationTypeDisplayName
    {
        public int ID { get; set; }
        public int EquationTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserTypeID { get; set; }
    
        public virtual EquationType EquationType { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
