//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSSDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nssEntities : DbContext
    {
        public nssEntities()
            : base("name=nssEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citation> Citations { get; set; }
        public virtual DbSet<Equation> Equations { get; set; }
        public virtual DbSet<EquationError> EquationErrors { get; set; }
        public virtual DbSet<EquationUnitType> EquationUnitTypes { get; set; }
        public virtual DbSet<ErrorType> ErrorTypes { get; set; }
        public virtual DbSet<PredictionInterval> PredictionIntervals { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<StatisticGroupType> StatisticGroupTypes { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
        public virtual DbSet<VariableType> VariableTypes { get; set; }
        public virtual DbSet<VariableUnitType> VariableUnitTypes { get; set; }
        public virtual DbSet<UnitConversionFactor> UnitConversionFactors { get; set; }
        public virtual DbSet<UnitSystemType> UnitSystemTypes { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
        public virtual DbSet<RegionRegressionRegion> RegionRegressionRegions { get; set; }
        public virtual DbSet<RegressionRegion> RegressionRegions { get; set; }
        public virtual DbSet<RegressionType> RegressionTypes { get; set; }
        public virtual DbSet<RegressionTypeDisplayName> RegressionTypeDisplayNames { get; set; }
    }
}
