//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversionFactor
    {
        public int ID { get; set; }
        public int UnitTypeInID { get; set; }
        public int UnitTypeOutID { get; set; }
        public double Factor { get; set; }
    
        public virtual UnitType UnitTypeIn { get; set; }
        public virtual UnitType UnitTypeOut { get; set; }
    }
}
