//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT
    {
        public int ID { get; set; }
        public int UNIT_TYPE { get; set; }
        public string UNIT1 { get; set; }
        public string ABBREVIATION { get; set; }
    }
}
