//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSSDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableUnitType
    {
        public int ID { get; set; }
        public int VariableID { get; set; }
        public int UnitTypeID { get; set; }
    
        public virtual Variable Variable { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
